package com.example.localization

object StringsProvider {

    fun get(key: StringKey, language: Language, vararg args: Any): String {
        val raw = translations[language]?.get(key)
            ?: translations[Language.ENGLISH]?.get(key)
            ?: key.name

        return if (args.isNotEmpty()) {
            try {
                String.format(raw, *args)
            } catch (e: Exception) {
                raw
            }
        } else {
            raw
        }
    }

    private val englishMap = mapOf(
        StringKey.APP_NAME to "SPY",
        StringKey.TAGLINE to "Can you find the Spy?",
        StringKey.PLAY to "PLAY",
        StringKey.CUSTOM_GAME to "CUSTOM GAME",
        StringKey.HOW_TO_PLAY to "HOW TO PLAY",
        StringKey.SETTINGS to "SETTINGS",
        StringKey.HISTORY to "MATCH HISTORY",
        StringKey.CUSTOM_WORDS to "CUSTOM WORDS",
        StringKey.START_GAME to "START GAME",
        StringKey.PLAYERS_COUNT to "Players",
        StringKey.SPIES_COUNT to "Spies",
        StringKey.PLAYER_NAMES to "Player Names",
        StringKey.ADD_PLAYER to "Add Player",
        StringKey.REMOVE_PLAYER to "Remove",
        StringKey.SPY_CLUES_TITLE to "Spy Clue Setting",
        StringKey.CLUE_NONE to "No Clue",
        StringKey.CLUE_NONE_DESC to "The spy receives zero information",
        StringKey.CLUE_CATEGORY to "Category Clue",
        StringKey.CLUE_CATEGORY_DESC to "The spy knows the word category",
        StringKey.CLUE_FIRST_LETTER to "First-Letter Clue",
        StringKey.CLUE_FIRST_LETTER_DESC to "The spy knows the first letter of the word",
        StringKey.CLUE_WORD_CATEGORY to "Word & Length Clue",
        StringKey.CLUE_WORD_CATEGORY_DESC to "The spy knows category and word length",
        StringKey.ROUND_SETTINGS to "Round Settings",
        StringKey.DISCUSSION_TIMER to "Discussion Timer",
        StringKey.TIMER_OFF to "Off",
        StringKey.TIMER_30S to "30s",
        StringKey.TIMER_60S to "60s",
        StringKey.TIMER_90S to "90s",
        StringKey.TIMER_2M to "2 min",
        StringKey.TIMER_CUSTOM to "Custom",
        StringKey.SOUND_EFFECTS to "Sound Effects",
        StringKey.VIBRATION to "Vibration / Haptics",
        StringKey.PREVENT_REPEATED_WORDS to "Prevent Repeated Words",
        StringKey.CATEGORIES_TITLE to "Word Categories",
        StringKey.SELECT_ALL to "Select All",
        StringKey.DESELECT_ALL to "Deselect All",
        StringKey.DIFFICULTY_TITLE to "Difficulty",
        StringKey.DIFF_EASY to "Easy",
        StringKey.DIFF_MEDIUM to "Medium",
        StringKey.DIFF_HARD to "Hard",
        StringKey.DIFF_EXTREME to "Extreme",
        StringKey.WORD_LENGTH_TITLE to "Word Length",
        StringKey.LENGTH_ANY to "Any Length",
        StringKey.LENGTH_SHORT to "Short (3-5 letters)",
        StringKey.LENGTH_MEDIUM to "Medium (6-8 letters)",
        StringKey.LENGTH_LONG to "Long (9+ letters)",
        StringKey.PASS_PHONE_TO to "PASS THE PHONE TO %s",
        StringKey.GET_READY_PROMPT to "Make sure nobody else is looking at the screen!",
        StringKey.REVEAL_MY_ROLE to "REVEAL MY ROLE",
        StringKey.YOU_ARE_INNOCENT to "YOU ARE INNOCENT",
        StringKey.YOU_ARE_SPY to "YOU ARE THE SPY",
        StringKey.SECRET_WORD_IS to "SECRET WORD",
        StringKey.CATEGORY_LABEL to "CATEGORY",
        StringKey.SPY_CLUE_LABEL to "SPY CLUE",
        StringKey.INNOCENT_HINT to "You know the secret word. Give clever, subtle clues without letting the Spy figure it out!",
        StringKey.SPY_HINT to "You don't know the word! Listen carefully to others, blend in, and try to guess the secret word!",
        StringKey.HIDE_AND_PASS to "HIDE & PASS PHONE",
        StringKey.ALL_ROLES_REVEALED_TITLE to "ALL PLAYERS ARE READY!",
        StringKey.ALL_ROLES_REVEALED_DESC to "Put the phone down on the table. Everyone will now discuss and give clues in real life.",
        StringKey.START_DISCUSSION to "START DISCUSSION",
        StringKey.DISCUSSION_TITLE to "DISCUSSION IN PROGRESS",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s starts giving the first clue!",
        StringKey.TIME_REMAINING to "Time Remaining",
        StringKey.PAUSE to "Pause",
        StringKey.RESUME to "Resume",
        StringKey.ADD_30S to "+30s",
        StringKey.TIME_TO_VOTE to "TIME TO VOTE",
        StringKey.TIME_TO_VOTE_TITLE to "Everyone Vote Now!",
        StringKey.TIME_TO_VOTE_DESC to "Discuss and point to the person the group suspects is the Spy.",
        StringKey.WHO_WAS_THE_SPY to "WHO WAS ACCUSED AS THE SPY?",
        StringKey.CONFIRM_ACCUSATION to "CONFIRM VOTE",
        StringKey.SPY_WAS_CAUGHT to "🔴 THE SPY WAS CAUGHT!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 AN INNOCENT WAS ACCUSED!",
        StringKey.SPY_LAST_CHANCE_TITLE to "THE SPY HAS ONE LAST CHANCE!",
        StringKey.SPY_LAST_CHANCE_DESC to "Can the Spy guess the secret word right now?",
        StringKey.SPY_GUESSED_CORRECT to "SPY GUESSED CORRECTLY",
        StringKey.SPY_GUESSED_WRONG to "SPY GUESSED WRONG",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ THE SPY STOLE THE WIN!",
        StringKey.PLAYERS_WIN to "🎉 THE INNOCENTS WIN!",
        StringKey.SPIES_WIN to "🕵️ THE SPIES WIN!",
        StringKey.REVEALED_WORD_WAS to "The secret word was:",
        StringKey.THE_REAL_SPIES_WERE to "The real Spy was:",
        StringKey.PLAY_NEXT_ROUND to "NEXT ROUND",
        StringKey.CHANGE_SETTINGS to "CHANGE SETTINGS",
        StringKey.RETURN_HOME to "HOME MENU",
        StringKey.RULE_1_TITLE to "1. Pass & Secret Roles",
        StringKey.RULE_1_DESC to "Pass the phone to each player. Each person taps to secretly view their role. Innocents see the secret word; the Spy sees nothing!",
        StringKey.RULE_2_TITLE to "2. Clues & Discussion",
        StringKey.RULE_2_DESC to "Put the phone on the table. Players take turns giving one subtle clue about the secret word in real life. The spy tries to blend in!",
        StringKey.RULE_3_TITLE to "3. Group Vote",
        StringKey.RULE_3_DESC to "When time is up, everyone votes in real life on who they think the Spy is. The host marks the accused player in the app.",
        StringKey.RULE_4_TITLE to "4. Spy's Last Chance",
        StringKey.RULE_4_DESC to "If the Spy is caught, they get one final attempt to guess the secret word. If they guess right, the Spy steals the win!",
        StringKey.SELECT_LANGUAGE to "Select Language",
        StringKey.LANGUAGE to "Language",
        StringKey.TOTAL_GAMES_PLAYED to "Total Games",
        StringKey.INNOCENT_WINS to "Innocent Wins",
        StringKey.SPY_WINS to "Spy Wins",
        StringKey.HOST_CLOUD_SYNC to "Host Cloud Backup (Optional)",
        StringKey.HOST_CLOUD_SYNC_DESC to "Sign in with Google to backup your party match records and custom words to Firebase Firestore.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Sign In with Google",
        StringKey.SIGNED_IN_AS to "Signed in as:",
        StringKey.SIGN_OUT to "Sign Out",
        StringKey.SYNC_NOW to "Sync Now",
        StringKey.SYNC_SUCCESS to "Data successfully backed up to cloud!",
        StringKey.ADD_NEW_WORD to "Add Custom Word",
        StringKey.WORD_INPUT_HINT to "Enter secret word...",
        StringKey.CATEGORY_INPUT_HINT to "Category name...",
        StringKey.SAVE_WORD to "Save Word",
        StringKey.DELETE_WORD to "Delete",
        StringKey.NO_CUSTOM_WORDS to "No custom words yet. Add your own words for party fun!",
        StringKey.BACK to "Back",
        StringKey.CLOSE to "Close",
        StringKey.SAVE to "Save",
        StringKey.CANCEL to "Cancel",
        StringKey.RESET to "Reset",
        StringKey.CONFIRM to "Confirm",
        StringKey.ERROR_MIN_PLAYERS to "At least 3 players are required!",
        StringKey.ERROR_TOO_MANY_SPIES to "Too many spies for the number of players!",
        StringKey.ERROR_SELECT_CATEGORY to "Please select at least one word category!",
        StringKey.CAT_ANIMALS to "Animals",
        StringKey.CAT_FOOD to "Food",
        StringKey.CAT_COUNTRIES to "Countries",
        StringKey.CAT_CITIES to "Cities",
        StringKey.CAT_OBJECTS to "Objects",
        StringKey.CAT_TECHNOLOGY to "Technology",
        StringKey.CAT_VIDEOGAMES to "Video Games",
        StringKey.CAT_MOVIES to "Movies",
        StringKey.CAT_SPORTS to "Sports",
        StringKey.CAT_CELEBRITIES to "Celebrities",
        StringKey.CAT_VEHICLES to "Vehicles",
        StringKey.CAT_NATURE to "Nature",
        StringKey.CAT_JOBS to "Jobs",
        StringKey.CAT_SCHOOL to "School",
        StringKey.CAT_RANDOM to "Random"
    )

    private val persianMap = mapOf(
        StringKey.APP_NAME to "جاسوس",
        StringKey.TAGLINE to "آیا می‌توانید جاسوس را پیدا کنید؟",
        StringKey.PLAY to "شروع بازی",
        StringKey.CUSTOM_GAME to "تنظیمات بازی",
        StringKey.HOW_TO_PLAY to "راهنمای بازی",
        StringKey.SETTINGS to "تنظیمات",
        StringKey.HISTORY to "تاریخچه بازی‌ها",
        StringKey.CUSTOM_WORDS to "کلمات اختصاصی",
        StringKey.START_GAME to "شروع دور بازی",
        StringKey.PLAYERS_COUNT to "تعداد بازیکنان",
        StringKey.SPIES_COUNT to "تعداد جاسوس‌ها",
        StringKey.PLAYER_NAMES to "نام بازیکنان",
        StringKey.ADD_PLAYER to "افزودن بازیکن",
        StringKey.REMOVE_PLAYER to "حذف",
        StringKey.SPY_CLUES_TITLE to "راهنمای جاسوس",
        StringKey.CLUE_NONE to "بدون راهنمایی",
        StringKey.CLUE_NONE_DESC to "جاسوس هیچ اطلاعی از کلمه ندارد",
        StringKey.CLUE_CATEGORY to "دسته‌بندی کلمه",
        StringKey.CLUE_CATEGORY_DESC to "جاسوس دسته‌بندی کلمه را می‌داند",
        StringKey.CLUE_FIRST_LETTER to "حرف اول کلمه",
        StringKey.CLUE_FIRST_LETTER_DESC to "جاسوس حرف اول کلمه مخفی را می‌داند",
        StringKey.CLUE_WORD_CATEGORY to "دسته و تعداد حروف",
        StringKey.CLUE_WORD_CATEGORY_DESC to "جاسوس دسته و طول کلمه را می‌داند",
        StringKey.ROUND_SETTINGS to "تنظیمات دور",
        StringKey.DISCUSSION_TIMER to "زمان بحث و گفتگو",
        StringKey.TIMER_OFF to "بدون زمان",
        StringKey.TIMER_30S to "۳۰ ثانیه",
        StringKey.TIMER_60S to "۱ دقیقه",
        StringKey.TIMER_90S to "۹۰ ثانیه",
        StringKey.TIMER_2M to "۲ دقیقه",
        StringKey.TIMER_CUSTOM to "سفارشی",
        StringKey.SOUND_EFFECTS to "افکت‌های صوتی",
        StringKey.VIBRATION to "لرزش (ویبره)",
        StringKey.PREVENT_REPEATED_WORDS to "جلوگیری از تکرار کلمات",
        StringKey.CATEGORIES_TITLE to "دسته‌بندی کلمات",
        StringKey.SELECT_ALL to "انتخاب همه",
        StringKey.DESELECT_ALL to "لغو همه",
        StringKey.DIFFICULTY_TITLE to "سطح سختی",
        StringKey.DIFF_EASY to "آسان",
        StringKey.DIFF_MEDIUM to "متوسط",
        StringKey.DIFF_HARD to "سخت",
        StringKey.DIFF_EXTREME to "بسیار سخت",
        StringKey.WORD_LENGTH_TITLE to "طول کلمه",
        StringKey.LENGTH_ANY to "هر طولی",
        StringKey.LENGTH_SHORT to "کوتاه (۳ تا ۵ حرف)",
        StringKey.LENGTH_MEDIUM to "متوسط (۶ تا ۸ حرف)",
        StringKey.LENGTH_LONG to "بلند (۹ حرف به بالا)",
        StringKey.PASS_PHONE_TO to "گوشی را به %s بدهید",
        StringKey.GET_READY_PROMPT to "مطمئن شوید هیچ‌کس صفحه گوشی را نمی‌بیند!",
        StringKey.REVEAL_MY_ROLE to "مشاهده نقش من",
        StringKey.YOU_ARE_INNOCENT to "🟢 شما بی‌گناه هستید",
        StringKey.YOU_ARE_SPY to "🔴 شما جاسوس هستید",
        StringKey.SECRET_WORD_IS to "کلمه مخفی",
        StringKey.CATEGORY_LABEL to "دسته‌بندی",
        StringKey.SPY_CLUE_LABEL to "سرنخ جاسوس",
        StringKey.INNOCENT_HINT to "شما کلمه مخفی را می‌دانید. سرنخ‌های هوشمندانه و نامحسوس بدهید تا جاسوس لو نرود!",
        StringKey.SPY_HINT to "شما کلمه را نمی‌دانید! با دقت به صحبت‌های دیگران گوش دهید و سعی کنید کلمه را حدس بزنید!",
        StringKey.HIDE_AND_PASS to "مخفی کن و گوشی را تحویل بده",
        StringKey.ALL_ROLES_REVEALED_TITLE to "همه بازیکنان نقش خود را دیدند!",
        StringKey.ALL_ROLES_REVEALED_DESC to "گوشی را روی میز بگذارید. گفتگو و سرنخ دادن در دنیای واقعی آغاز شد.",
        StringKey.START_DISCUSSION to "آغاز گفتگو",
        StringKey.DISCUSSION_TITLE to "زمان گفتگو و سرنخ",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s اولین سرنخ را شروع می‌کند!",
        StringKey.TIME_REMAINING to "زمان باقی‌مانده",
        StringKey.PAUSE to "توقف",
        StringKey.RESUME to "ادامه",
        StringKey.ADD_30S to "+۳۰ ثانیه",
        StringKey.TIME_TO_VOTE to "زمان رای‌گیری",
        StringKey.TIME_TO_VOTE_TITLE to "همه رأی دهید!",
        StringKey.TIME_TO_VOTE_DESC to "در واقعیت با هم صحبت کنید و به فردی که مشکوک به جاسوسی است اشاره کنید.",
        StringKey.WHO_WAS_THE_SPY to "چه کسی به عنوان جاسوس متهم شد؟",
        StringKey.CONFIRM_ACCUSATION to "ثبت رای گروه",
        StringKey.SPY_WAS_CAUGHT to "🔴 جاسوس دستگیر شد!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 یک بی‌گناه اشتباهاً متهم شد!",
        StringKey.SPY_LAST_CHANCE_TITLE to "جاسوس یک شانس آخر دارد!",
        StringKey.SPY_LAST_CHANCE_DESC to "آیا جاسوس توانست کلمه مخفی را به درستی حدس بزند؟",
        StringKey.SPY_GUESSED_CORRECT to "جاسوس درست حدس زد",
        StringKey.SPY_GUESSED_WRONG to "جاسوس اشتباه حدس زد",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ جاسوس کلمه را حدس زد و برنده شد!",
        StringKey.PLAYERS_WIN to "🎉 بی‌گناهان پیروز شدند!",
        StringKey.SPIES_WIN to "🕵️ جاسوسان برنده شدند!",
        StringKey.REVEALED_WORD_WAS to "کلمه مخفی این بود:",
        StringKey.THE_REAL_SPIES_WERE to "جاسوس اصلی بازی:",
        StringKey.PLAY_NEXT_ROUND to "دور بعدی",
        StringKey.CHANGE_SETTINGS to "تغییر تنظیمات",
        StringKey.RETURN_HOME to "منوی اصلی",
        StringKey.RULE_1_TITLE to "۱. دست به دست کردن گوشی",
        StringKey.RULE_1_DESC to "گوشی را به ترتیب به هر بازیکن بدهید. هر فرد دکمه را می‌زند تا نقشش را ببیند. افراد عادی کلمه مخفی را می‌بینند؛ جاسوس کلمه را نمی‌بیند!",
        StringKey.RULE_2_TITLE to "۲. دادن سرنخ و گفتگو",
        StringKey.RULE_2_DESC to "گوشی را کنار بگذارید. بازیکنان به نوبت در دنیای واقعی یک سرنخ ظریف از کلمه می‌دهند. جاسوس باید طوری حرف بزند که لو نرود!",
        StringKey.RULE_3_TITLE to "۳. رأی‌گیری",
        StringKey.RULE_3_DESC to "پس از اتمام زمان، همه به شخصی که فکر می‌کنند جاسوس است رأی می‌دهند و میزبان نتیجه را در برنامه ثبت می‌کند.",
        StringKey.RULE_4_TITLE to "۴. آخرین شانس جاسوس",
        StringKey.RULE_4_DESC to "اگر جاسوس لو برود، یک شانس نهایی دارد تا کلمه مخفی را حدس بزند. اگر درست حدس بزند، پیروزی را از آن خود می‌کند!",
        StringKey.SELECT_LANGUAGE to "انتخاب زبان",
        StringKey.LANGUAGE to "زبان",
        StringKey.TOTAL_GAMES_PLAYED to "تعداد کل بازی‌ها",
        StringKey.INNOCENT_WINS to "بردهای بی‌گناهان",
        StringKey.SPY_WINS to "بردهای جاسوس",
        StringKey.HOST_CLOUD_SYNC to "پشتیبان‌گیری ابری میزبان (اختیاری)",
        StringKey.HOST_CLOUD_SYNC_DESC to "با حساب گوگل وارد شوید تا آمار بازی‌ها و کلمات دلخواه شما در پایگاه ابری فایربیس ذخیره شوند.",
        StringKey.SIGN_IN_WITH_GOOGLE to "ورود با حساب گوگل",
        StringKey.SIGNED_IN_AS to "وارد شده با عنوان:",
        StringKey.SIGN_OUT to "خروج از حساب",
        StringKey.SYNC_NOW to "همگام‌سازی ابری",
        StringKey.SYNC_SUCCESS to "اطلاعات با موفقیت در فضای ابری ذخیره شد!",
        StringKey.ADD_NEW_WORD to "افزودن کلمه جدید",
        StringKey.WORD_INPUT_HINT to "کلمه مخفی مورد نظر...",
        StringKey.CATEGORY_INPUT_HINT to "نام دسته‌بندی...",
        StringKey.SAVE_WORD to "ذخیره کلمه",
        StringKey.DELETE_WORD to "حذف",
        StringKey.NO_CUSTOM_WORDS to "هنوز کلمه اختصاصی اضافه نکرده‌اید.",
        StringKey.BACK to "بازگشت",
        StringKey.CLOSE to "بستن",
        StringKey.SAVE to "ذخیره",
        StringKey.CANCEL to "انصراف",
        StringKey.RESET to "بازنشانی",
        StringKey.CONFIRM to "تایید",
        StringKey.ERROR_MIN_PLAYERS to "حداقل ۳ بازیکن برای بازی لازم است!",
        StringKey.ERROR_TOO_MANY_SPIES to "تعداد جاسوس‌ها نسبت به بازیکنان زیاد است!",
        StringKey.ERROR_SELECT_CATEGORY to "لطفاً حداقل یک دسته‌بندی انتخاب کنید!",
        StringKey.CAT_ANIMALS to "حیوانات",
        StringKey.CAT_FOOD to "غذا و خوراکی",
        StringKey.CAT_COUNTRIES to "کشورها",
        StringKey.CAT_CITIES to "شهرها",
        StringKey.CAT_OBJECTS to "اشیاء",
        StringKey.CAT_TECHNOLOGY to "فناوری و گجت",
        StringKey.CAT_VIDEOGAMES to "بازی‌های ویدیویی",
        StringKey.CAT_MOVIES to "فیلم و سینما",
        StringKey.CAT_SPORTS to "ورزش‌ها",
        StringKey.CAT_CELEBRITIES to "افراد مشهور",
        StringKey.CAT_VEHICLES to "وسایل نقلیه",
        StringKey.CAT_NATURE to "طبیعت",
        StringKey.CAT_JOBS to "مشاغل",
        StringKey.CAT_SCHOOL to "مدرسه و دانشگاه",
        StringKey.CAT_RANDOM to "تصادفی"
    )

    private val arabicMap = mapOf(
        StringKey.APP_NAME to "الجاسوس",
        StringKey.TAGLINE to "هل يمكنك كشف الجاسوس؟",
        StringKey.PLAY to "بدء اللعب",
        StringKey.CUSTOM_GAME to "لعبة مخصصة",
        StringKey.HOW_TO_PLAY to "كيفية اللعب",
        StringKey.SETTINGS to "الإعدادات",
        StringKey.HISTORY to "سجل المباريات",
        StringKey.CUSTOM_WORDS to "كلمات مخصصة",
        StringKey.START_GAME to "بدء الجولة",
        StringKey.PLAYERS_COUNT to "اللاعبين",
        StringKey.SPIES_COUNT to "الجواسيس",
        StringKey.PLAYER_NAMES to "أسماء اللاعبين",
        StringKey.ADD_PLAYER to "إضافة لاعب",
        StringKey.REMOVE_PLAYER to "حذف",
        StringKey.SPY_CLUES_TITLE to "تلميح الجاسوس",
        StringKey.CLUE_NONE to "بدون تلميح",
        StringKey.CLUE_NONE_DESC to "الجاسوس لا يعلم أي شيء عن الكلمة",
        StringKey.CLUE_CATEGORY to "تلميح التصنيف",
        StringKey.CLUE_CATEGORY_DESC to "الجاسوس يعرف تصنيف الكلمة",
        StringKey.CLUE_FIRST_LETTER to "تلميح الحرف الأول",
        StringKey.CLUE_FIRST_LETTER_DESC to "الجاسوس يعرف أول حرف من الكلمة",
        StringKey.CLUE_WORD_CATEGORY to "التصنيف وعدد الحروف",
        StringKey.CLUE_WORD_CATEGORY_DESC to "الجاسوس يعرف التصنيف وعدد الحروف",
        StringKey.ROUND_SETTINGS to "إعدادات الجولة",
        StringKey.DISCUSSION_TIMER to "مؤقت النقاش",
        StringKey.TIMER_OFF to "معطل",
        StringKey.TIMER_30S to "٣٠ ثانية",
        StringKey.TIMER_60S to "دقيقة",
        StringKey.TIMER_90S to "٩٠ ثانية",
        StringKey.TIMER_2M to "دقيقتان",
        StringKey.TIMER_CUSTOM to "مخصص",
        StringKey.SOUND_EFFECTS to "المؤثرات الصوتية",
        StringKey.VIBRATION to "الاهتزاز",
        StringKey.PREVENT_REPEATED_WORDS to "منع تكرار الكلمات",
        StringKey.CATEGORIES_TITLE to "تصنيفات الكلمات",
        StringKey.SELECT_ALL to "تحديد الكل",
        StringKey.DESELECT_ALL to "إلغاء الكل",
        StringKey.DIFFICULTY_TITLE to "المستوى",
        StringKey.DIFF_EASY to "سهل",
        StringKey.DIFF_MEDIUM to "متوسط",
        StringKey.DIFF_HARD to "صعب",
        StringKey.DIFF_EXTREME to "شديد الصعوبة",
        StringKey.WORD_LENGTH_TITLE to "طول الكلمة",
        StringKey.LENGTH_ANY to "أي طول",
        StringKey.LENGTH_SHORT to "قصير (٣-٥ حروف)",
        StringKey.LENGTH_MEDIUM to "متوسط (٦-٨ حروف)",
        StringKey.LENGTH_LONG to "طويل (+٩ حروف)",
        StringKey.PASS_PHONE_TO to "مرر الهاتف إلى %s",
        StringKey.GET_READY_PROMPT to "تأكد ألا ينظر أحد إلى الشاشة سواك!",
        StringKey.REVEAL_MY_ROLE to "إظهار دوري",
        StringKey.YOU_ARE_INNOCENT to "🟢 أنت بريء",
        StringKey.YOU_ARE_SPY to "🔴 أنت الجاسوس",
        StringKey.SECRET_WORD_IS to "الكلمة السرية",
        StringKey.CATEGORY_LABEL to "التصنيف",
        StringKey.SPY_CLUE_LABEL to "تلميح الجاسوس",
        StringKey.INNOCENT_HINT to "أنت تعرف الكلمة. أعطِ تلميحات ذكية دون أن يعرفها الجاسوس!",
        StringKey.SPY_HINT to "أنت لا تعرف الكلمة! استمع جيداً وحاول تخمين الكلمة والاندماج معهم!",
        StringKey.HIDE_AND_PASS to "إخفاء وتمرير الهاتف",
        StringKey.ALL_ROLES_REVEALED_TITLE to "جميع اللاعبين جاهزون!",
        StringKey.ALL_ROLES_REVEALED_DESC to "ضع الهاتف على الطاولة وابدأوا النقاش بالواقع.",
        StringKey.START_DISCUSSION to "بدء النقاش",
        StringKey.DISCUSSION_TITLE to "النقاش جارٍ",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s يبدأ بإعطاء أول تلميح!",
        StringKey.TIME_REMAINING to "الوقت المتبقي",
        StringKey.PAUSE to "إيقاف",
        StringKey.RESUME to "استئناف",
        StringKey.ADD_30S to "+٣٠ ثانية",
        StringKey.TIME_TO_VOTE to "حان وقت التصويت",
        StringKey.TIME_TO_VOTE_TITLE to "صوتوا الآن!",
        StringKey.TIME_TO_VOTE_DESC to "تشاوروا وأشيروا إلى الشخص المشتبه بكونه الجاسوس.",
        StringKey.WHO_WAS_THE_SPY to "من تم اتهامه بالجاسوسية؟",
        StringKey.CONFIRM_ACCUSATION to "تأكيد التصويت",
        StringKey.SPY_WAS_CAUGHT to "🔴 تم كشف الجاسوس!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 تم اتهام بريء!",
        StringKey.SPY_LAST_CHANCE_TITLE to "فرصة أخيرة للجاسوس!",
        StringKey.SPY_LAST_CHANCE_DESC to "هل استطاع الجاسوس تخمين الكلمة السرية؟",
        StringKey.SPY_GUESSED_CORRECT to "خمن الجاسوس الكلمة بشكل صحيح",
        StringKey.SPY_GUESSED_WRONG to "أخطأ الجاسوس في التخمين",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ الجاسوس سرق الفوز بالتخمين!",
        StringKey.PLAYERS_WIN to "🎉 فاز الأبرياء!",
        StringKey.SPIES_WIN to "🕵️ فاز الجواسيس!",
        StringKey.REVEALED_WORD_WAS to "الكلمة السرية كانت:",
        StringKey.THE_REAL_SPIES_WERE to "الجاسوس الحقيقي:",
        StringKey.PLAY_NEXT_ROUND to "الجولة التالية",
        StringKey.CHANGE_SETTINGS to "تعديل الإعدادات",
        StringKey.RETURN_HOME to "القائمة الرئيسية",
        StringKey.RULE_1_TITLE to "١. تمرير الهاتف والأدوار",
        StringKey.RULE_1_DESC to "مرر الهاتف لكل لاعب ليرى دوره بسرية. الأبرياء يرون الكلمة والجاسوس لا يرى الكلمة!",
        StringKey.RULE_2_TITLE to "٢. التلميحات والنقاش",
        StringKey.RULE_2_DESC to "ضع الهاتف جانباً، ويعطي كل لاعب تلميحاً ذكياً في الحياة الواقعية.",
        StringKey.RULE_3_TITLE to "٣. التصويت",
        StringKey.RULE_3_DESC to "صوتوا على من تعتقدون أنه الجاسوس، ويختار المضيف اللاعب المتهم في التطبيق.",
        StringKey.RULE_4_TITLE to "٤. فرصة الجاسوس الأخيرة",
        StringKey.RULE_4_DESC to "إذا تم كشف الجاسوس، يحصل على فرصة واحدة لتخمين الكلمة السرية والفوز!",
        StringKey.SELECT_LANGUAGE to "اختيار اللغة",
        StringKey.LANGUAGE to "اللغة",
        StringKey.TOTAL_GAMES_PLAYED to "إجمالي المباريات",
        StringKey.INNOCENT_WINS to "فوز الأبرياء",
        StringKey.SPY_WINS to "فوز الجواسيس",
        StringKey.HOST_CLOUD_SYNC to "النسخ الاحتياطي السحابي (اختياري)",
        StringKey.HOST_CLOUD_SYNC_DESC to "سجل دخولك بحساب Google لمزامنة إحصائياتك والكلمات المخصصة.",
        StringKey.SIGN_IN_WITH_GOOGLE to "تسجيل الدخول عبر Google",
        StringKey.SIGNED_IN_AS to "مسجل الدخول باسم:",
        StringKey.SIGN_OUT to "تسجيل الخروج",
        StringKey.SYNC_NOW to "مزامنة الآن",
        StringKey.SYNC_SUCCESS to "تمت المزامنة بنجاح!",
        StringKey.ADD_NEW_WORD to "إضافة كلمة",
        StringKey.WORD_INPUT_HINT to "الكلمة السرية...",
        StringKey.CATEGORY_INPUT_HINT to "اسم التصنيف...",
        StringKey.SAVE_WORD to "حفظ الكلمة",
        StringKey.DELETE_WORD to "حذف",
        StringKey.NO_CUSTOM_WORDS to "لا توجد كلمات مخصصة بعد.",
        StringKey.BACK to "رجوع",
        StringKey.CLOSE to "إغلاق",
        StringKey.SAVE to "حفظ",
        StringKey.CANCEL to "إلغاء",
        StringKey.RESET to "إعادة ضبط",
        StringKey.CONFIRM to "تأكيد",
        StringKey.ERROR_MIN_PLAYERS to "مطلوب ٣ لاعبين على الأقل!",
        StringKey.ERROR_TOO_MANY_SPIES to "عدد الجواسيس كبير بالنسبة لعدد اللاعبين!",
        StringKey.ERROR_SELECT_CATEGORY to "يرجى تحديد تصنيف واحد على الأقل!",
        StringKey.CAT_ANIMALS to "حيوانات",
        StringKey.CAT_FOOD to "طعام",
        StringKey.CAT_COUNTRIES to "دول",
        StringKey.CAT_CITIES to "مدن",
        StringKey.CAT_OBJECTS to "أشياء",
        StringKey.CAT_TECHNOLOGY to "تكنولوجيا",
        StringKey.CAT_VIDEOGAMES to "ألعاب فيديو",
        StringKey.CAT_MOVIES to "أفلام",
        StringKey.CAT_SPORTS to "رياضة",
        StringKey.CAT_CELEBRITIES to "مشاهير",
        StringKey.CAT_VEHICLES to "مركبات",
        StringKey.CAT_NATURE to "طبيعة",
        StringKey.CAT_JOBS to "وظائف",
        StringKey.CAT_SCHOOL to "مدرسة وجامعة",
        StringKey.CAT_RANDOM to "عشوائي"
    )

    private val spanishMap = mapOf(
        StringKey.APP_NAME to "ESPÍA",
        StringKey.TAGLINE to "¿Puedes encontrar al Espía?",
        StringKey.PLAY to "JUGAR",
        StringKey.CUSTOM_GAME to "PARTIDA PERSONALIZADA",
        StringKey.HOW_TO_PLAY to "CÓMO JUGAR",
        StringKey.SETTINGS to "AJUSTES",
        StringKey.HISTORY to "HISTORIAL",
        StringKey.CUSTOM_WORDS to "PALABRAS PROPIAS",
        StringKey.START_GAME to "EMPEZAR PARTIDA",
        StringKey.PLAYERS_COUNT to "Jugadores",
        StringKey.SPIES_COUNT to "Espías",
        StringKey.PLAYER_NAMES to "Nombres de Jugadores",
        StringKey.ADD_PLAYER to "Añadir Jugador",
        StringKey.REMOVE_PLAYER to "Eliminar",
        StringKey.SPY_CLUES_TITLE to "Pistas para el Espía",
        StringKey.CLUE_NONE to "Sin pistas",
        StringKey.CLUE_NONE_DESC to "El espía no recibe información",
        StringKey.CLUE_CATEGORY to "Pista de Categoría",
        StringKey.CLUE_CATEGORY_DESC to "El espía conoce la categoría",
        StringKey.CLUE_FIRST_LETTER to "Pista de Primera Letra",
        StringKey.CLUE_FIRST_LETTER_DESC to "El espía conoce la primera letra",
        StringKey.CLUE_WORD_CATEGORY to "Categoría y Longitud",
        StringKey.CLUE_WORD_CATEGORY_DESC to "El espía conoce categoría y longitud",
        StringKey.ROUND_SETTINGS to "Ajustes de Ronda",
        StringKey.DISCUSSION_TIMER to "Temporizador de Debate",
        StringKey.TIMER_OFF to "Desactivado",
        StringKey.TIMER_30S to "30s",
        StringKey.TIMER_60S to "60s",
        StringKey.TIMER_90S to "90s",
        StringKey.TIMER_2M to "2 min",
        StringKey.TIMER_CUSTOM to "Personalizado",
        StringKey.SOUND_EFFECTS to "Efectos de Sonido",
        StringKey.VIBRATION to "Vibración",
        StringKey.PREVENT_REPEATED_WORDS to "Evitar Palabras Repetidas",
        StringKey.CATEGORIES_TITLE to "Categorías de Palabras",
        StringKey.SELECT_ALL to "Seleccionar Todo",
        StringKey.DESELECT_ALL to "Deseleccionar Todo",
        StringKey.DIFFICULTY_TITLE to "Dificultad",
        StringKey.DIFF_EASY to "Fácil",
        StringKey.DIFF_MEDIUM to "Media",
        StringKey.DIFF_HARD to "Difícil",
        StringKey.DIFF_EXTREME to "Extrema",
        StringKey.WORD_LENGTH_TITLE to "Longitud de Palabra",
        StringKey.LENGTH_ANY to "Cualquier longitud",
        StringKey.LENGTH_SHORT to "Corta (3-5 letras)",
        StringKey.LENGTH_MEDIUM to "Media (6-8 letras)",
        StringKey.LENGTH_LONG to "Larga (+9 letras)",
        StringKey.PASS_PHONE_TO to "PASA EL TELÉFONO A %s",
        StringKey.GET_READY_PROMPT to "¡Asegúrate de que nadie más mire la pantalla!",
        StringKey.REVEAL_MY_ROLE to "REVELAR MI ROL",
        StringKey.YOU_ARE_INNOCENT to "🟢 ERES INOCENTE",
        StringKey.YOU_ARE_SPY to "🔴 ERES EL ESPÍA",
        StringKey.SECRET_WORD_IS to "PALABRA SECRETA",
        StringKey.CATEGORY_LABEL to "CATEGORÍA",
        StringKey.SPY_CLUE_LABEL to "PISTA DEL ESPÍA",
        StringKey.INNOCENT_HINT to "Conoces la palabra secreta. ¡Da pistas sutiles sin que el espía la descubra!",
        StringKey.SPY_HINT to "¡No conoces la palabra! Escucha atentamente, disimula e intenta adivinarla.",
        StringKey.HIDE_AND_PASS to "OCULTAR Y PASAR TELÉFONO",
        StringKey.ALL_ROLES_REVEALED_TITLE to "¡TODOS ESTÁN LISTOS!",
        StringKey.ALL_ROLES_REVEALED_DESC to "Dejad el teléfono sobre la mesa. Comenzad a debatir y dar pistas en la vida real.",
        StringKey.START_DISCUSSION to "INICIAR DEBATE",
        StringKey.DISCUSSION_TITLE to "DEBATE EN CURSO",
        StringKey.FIRST_CLUE_PROMPT to "🎲 ¡%s da la primera pista!",
        StringKey.TIME_REMAINING to "Tiempo Restante",
        StringKey.PAUSE to "Pausar",
        StringKey.RESUME to "Reanudar",
        StringKey.ADD_30S to "+30s",
        StringKey.TIME_TO_VOTE to "HORA DE VOTAR",
        StringKey.TIME_TO_VOTE_TITLE to "¡Todos voten ahora!",
        StringKey.TIME_TO_VOTE_DESC to "Debatid y señalad a quien creáis que es el espía.",
        StringKey.WHO_WAS_THE_SPY to "¿QUIÉN FUE ACUSADO COMO ESPÍA?",
        StringKey.CONFIRM_ACCUSATION to "CONFIRMAR VOTO",
        StringKey.SPY_WAS_CAUGHT to "🔴 ¡EL ESPÍA FUE ATRAPADO!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 ¡SE ACUSÓ A UN INOCENTE!",
        StringKey.SPY_LAST_CHANCE_TITLE to "¡ÚLTIMA OPORTUNIDAD DEL ESPÍA!",
        StringKey.SPY_LAST_CHANCE_DESC to "¿Logró el espía adivinar la palabra secreta?",
        StringKey.SPY_GUESSED_CORRECT to "EL ESPÍA ACERTÓ",
        StringKey.SPY_GUESSED_WRONG to "EL ESPÍA FALLÓ",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ ¡EL ESPÍA ROBÓ LA VICTORIA!",
        StringKey.PLAYERS_WIN to "🎉 ¡LOS INOCENTES GANAN!",
        StringKey.SPIES_WIN to "🕵️ ¡LOS ESPÍAS GANAN!",
        StringKey.REVEALED_WORD_WAS to "La palabra secreta era:",
        StringKey.THE_REAL_SPIES_WERE to "El verdadero espía era:",
        StringKey.PLAY_NEXT_ROUND to "SIGUIENTE RONDA",
        StringKey.CHANGE_SETTINGS to "CAMBIAR AJUSTES",
        StringKey.RETURN_HOME to "MENÚ PRINCIPAL",
        StringKey.RULE_1_TITLE to "1. Pasar teléfono y roles",
        StringKey.RULE_1_DESC to "Pasa el móvil a cada jugador. Cada uno pulsa para ver su rol en secreto.",
        StringKey.RULE_2_TITLE to "2. Pistas y debate",
        StringKey.RULE_2_DESC to "Dejad el móvil. Cada jugador da una pista sutil en la vida real.",
        StringKey.RULE_3_TITLE to "3. Votación",
        StringKey.RULE_3_DESC to "Votad quién creéis que es el espía y el anfitrión lo registra.",
        StringKey.RULE_4_TITLE to "4. Última oportunidad",
        StringKey.RULE_4_DESC to "Si pillan al espía, tiene un último intento de adivinar la palabra para ganar.",
        StringKey.SELECT_LANGUAGE to "Seleccionar Idioma",
        StringKey.LANGUAGE to "Idioma",
        StringKey.TOTAL_GAMES_PLAYED to "Partidas Jugadas",
        StringKey.INNOCENT_WINS to "Victorias Inocentes",
        StringKey.SPY_WINS to "Victorias Espías",
        StringKey.HOST_CLOUD_SYNC to "Copia de Seguridad en la Nube (Opcional)",
        StringKey.HOST_CLOUD_SYNC_DESC to "Inicia sesión con Google para guardar tus partidas en Firebase.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Iniciar sesión con Google",
        StringKey.SIGNED_IN_AS to "Conectado como:",
        StringKey.SIGN_OUT to "Cerrar sesión",
        StringKey.SYNC_NOW to "Sincronizar",
        StringKey.SYNC_SUCCESS to "¡Datos sincronizados con éxito!",
        StringKey.ADD_NEW_WORD to "Añadir Palabra",
        StringKey.WORD_INPUT_HINT to "Palabra secreta...",
        StringKey.CATEGORY_INPUT_HINT to "Categoría...",
        StringKey.SAVE_WORD to "Guardar",
        StringKey.DELETE_WORD to "Eliminar",
        StringKey.NO_CUSTOM_WORDS to "Sin palabras personalizadas aún.",
        StringKey.BACK to "Atrás",
        StringKey.CLOSE to "Cerrar",
        StringKey.SAVE to "Guardar",
        StringKey.CANCEL to "Cancelar",
        StringKey.RESET to "Reiniciar",
        StringKey.CONFIRM to "Confirmar",
        StringKey.ERROR_MIN_PLAYERS to "¡Se necesitan al menos 3 jugadores!",
        StringKey.ERROR_TOO_MANY_SPIES to "¡Demasiados espías para los jugadores!",
        StringKey.ERROR_SELECT_CATEGORY to "¡Elige al menos una categoría!",
        StringKey.CAT_ANIMALS to "Animales",
        StringKey.CAT_FOOD to "Comida",
        StringKey.CAT_COUNTRIES to "Países",
        StringKey.CAT_CITIES to "Ciudades",
        StringKey.CAT_OBJECTS to "Objetos",
        StringKey.CAT_TECHNOLOGY to "Tecnología",
        StringKey.CAT_VIDEOGAMES to "Videojuegos",
        StringKey.CAT_MOVIES to "Películas",
        StringKey.CAT_SPORTS to "Deportes",
        StringKey.CAT_CELEBRITIES to "Famosos",
        StringKey.CAT_VEHICLES to "Vehículos",
        StringKey.CAT_NATURE to "Naturaleza",
        StringKey.CAT_JOBS to "Profesiones",
        StringKey.CAT_SCHOOL to "Escuela",
        StringKey.CAT_RANDOM to "Aleatorio"
    )

    private val frenchMap = mapOf(
        StringKey.APP_NAME to "ESPION",
        StringKey.TAGLINE to "Pouvez-vous trouver l'Espion ?",
        StringKey.PLAY to "JOUER",
        StringKey.CUSTOM_GAME to "PARTIE PERSONNALISÉE",
        StringKey.HOW_TO_PLAY to "COMMENT JOUER",
        StringKey.SETTINGS to "PARAMÈTRES",
        StringKey.HISTORY to "HISTORIQUE",
        StringKey.CUSTOM_WORDS to "MOTS PERSONNALISÉS",
        StringKey.START_GAME to "LANCER LA PARTIE",
        StringKey.PLAYERS_COUNT to "Joueurs",
        StringKey.SPIES_COUNT to "Espions",
        StringKey.PLAYER_NAMES to "Noms des joueurs",
        StringKey.ADD_PLAYER to "Ajouter un joueur",
        StringKey.REMOVE_PLAYER to "Supprimer",
        StringKey.SPY_CLUES_TITLE to "Indices pour l'Espion",
        StringKey.CLUE_NONE to "Aucun indice",
        StringKey.CLUE_NONE_DESC to "L'espion ne reçoit aucune information",
        StringKey.CLUE_CATEGORY to "Indice de Catégorie",
        StringKey.CLUE_CATEGORY_DESC to "L'espion connaît la catégorie du mot",
        StringKey.CLUE_FIRST_LETTER to "Première Lettre",
        StringKey.CLUE_FIRST_LETTER_DESC to "L'espion connaît la 1ère lettre",
        StringKey.CLUE_WORD_CATEGORY to "Catégorie et Longueur",
        StringKey.CLUE_WORD_CATEGORY_DESC to "L'espion connaît catégorie et taille",
        StringKey.ROUND_SETTINGS to "Paramètres du Tour",
        StringKey.DISCUSSION_TIMER to "Minuteur de Débat",
        StringKey.TIMER_OFF to "Désactivé",
        StringKey.TIMER_30S to "30s",
        StringKey.TIMER_60S to "60s",
        StringKey.TIMER_90S to "90s",
        StringKey.TIMER_2M to "2 min",
        StringKey.TIMER_CUSTOM to "Personnalisé",
        StringKey.SOUND_EFFECTS to "Effets Sonores",
        StringKey.VIBRATION to "Vibrations",
        StringKey.PREVENT_REPEATED_WORDS to "Éviter les Répétitions",
        StringKey.CATEGORIES_TITLE to "Catégories",
        StringKey.SELECT_ALL to "Tout sélectionner",
        StringKey.DESELECT_ALL to "Tout désélectionner",
        StringKey.DIFFICULTY_TITLE to "Difficulté",
        StringKey.DIFF_EASY to "Facile",
        StringKey.DIFF_MEDIUM to "Moyen",
        StringKey.DIFF_HARD to "Difficile",
        StringKey.DIFF_EXTREME to "Extrême",
        StringKey.WORD_LENGTH_TITLE to "Longueur du Mot",
        StringKey.LENGTH_ANY to "Toute longueur",
        StringKey.LENGTH_SHORT to "Court (3-5 lettres)",
        StringKey.LENGTH_MEDIUM to "Moyen (6-8 lettres)",
        StringKey.LENGTH_LONG to "Long (+9 lettres)",
        StringKey.PASS_PHONE_TO to "PASSEZ LE TÉLÉPHONE À %s",
        StringKey.GET_READY_PROMPT to "Assurez-vous que personne d'autre ne regarde !",
        StringKey.REVEAL_MY_ROLE to "RÉVÉLER MON RÔLE",
        StringKey.YOU_ARE_INNOCENT to "🟢 VOUS ÊTES INNOCENT",
        StringKey.YOU_ARE_SPY to "🔴 VOUS ÊTES L'ESPION",
        StringKey.SECRET_WORD_IS to "MOT SECRET",
        StringKey.CATEGORY_LABEL to "CATÉGORIE",
        StringKey.SPY_CLUE_LABEL to "INDICE ESPION",
        StringKey.INNOCENT_HINT to "Vous connaissez le mot secret. Donnez des indices subtils sans vous faire griller !",
        StringKey.SPY_HINT to "Vous ne connaissez pas le mot ! Écoutez les autres, fondez-vous dans la masse !",
        StringKey.HIDE_AND_PASS to "MASQUER ET PASSER LE TÉLÉPHONE",
        StringKey.ALL_ROLES_REVEALED_TITLE to "TOUT LE MONDE EST PRÊT !",
        StringKey.ALL_ROLES_REVEALED_DESC to "Posez le téléphone sur la table. Lancez le débat dans la vraie vie !",
        StringKey.START_DISCUSSION to "COMMENCER LE DÉBAT",
        StringKey.DISCUSSION_TITLE to "DÉBAT EN COURS",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s donne le premier indice !",
        StringKey.TIME_REMAINING to "Temps Restant",
        StringKey.PAUSE to "Pause",
        StringKey.RESUME to "Reprendre",
        StringKey.ADD_30S to "+30s",
        StringKey.TIME_TO_VOTE to "L'HEURE DU VOTE",
        StringKey.TIME_TO_VOTE_TITLE to "Votez tous maintenant !",
        StringKey.TIME_TO_VOTE_DESC to "Discutez et désignez du doigt le suspect.",
        StringKey.WHO_WAS_THE_SPY to "QUI A ÉTÉ ACCUSÉ D'ÊTRE L'ESPION ?",
        StringKey.CONFIRM_ACCUSATION to "CONFIRMER LE VOTE",
        StringKey.SPY_WAS_CAUGHT to "🔴 L'ESPION A ÉTÉ DÉMASQUÉ !",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 UN INNOCENT A ÉTÉ ACCUSÉ !",
        StringKey.SPY_LAST_CHANCE_TITLE to "DERNIÈRE CHANCE DE L'ESPION !",
        StringKey.SPY_LAST_CHANCE_DESC to "L'espion parvient-il à deviner le mot secret ?",
        StringKey.SPY_GUESSED_CORRECT to "L'ESPION A DEVINÉ",
        StringKey.SPY_GUESSED_WRONG to "L'ESPION S'EST TROMPÉ",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ L'ESPION VOLE LA VICTOIRE !",
        StringKey.PLAYERS_WIN to "🎉 LES INNOCENTS GAGNENT !",
        StringKey.SPIES_WIN to "🕵️ LES ESPIONS GAGNENT !",
        StringKey.REVEALED_WORD_WAS to "Le mot secret était :",
        StringKey.THE_REAL_SPIES_WERE to "Le véritable espion était :",
        StringKey.PLAY_NEXT_ROUND to "TOUR SUIVANT",
        StringKey.CHANGE_SETTINGS to "MODIFIER PARAMÈTRES",
        StringKey.RETURN_HOME to "ACCUEIL",
        StringKey.RULE_1_TITLE to "1. Passez le téléphone",
        StringKey.RULE_1_DESC to "Chaque joueur regarde discrètement son rôle. Les innocents voient le mot, l'espion ne voit rien !",
        StringKey.RULE_2_TITLE to "2. Indices et débat",
        StringKey.RULE_2_DESC to "Posez le téléphone. Chacun donne un indice subtil à voix haute.",
        StringKey.RULE_3_TITLE to "3. Le vote",
        StringKey.RULE_3_DESC to "Tout le monde vote pour désigner l'espion et l'hôte valide sur l'écran.",
        StringKey.RULE_4_TITLE to "4. Dernière chance",
        StringKey.RULE_4_DESC to "Si l'espion est attrapé, il peut tenter de deviner le mot pour rafler la victoire !",
        StringKey.SELECT_LANGUAGE to "Choisir la Langue",
        StringKey.LANGUAGE to "Langue",
        StringKey.TOTAL_GAMES_PLAYED to "Parties Jouées",
        StringKey.INNOCENT_WINS to "Victoires Innocents",
        StringKey.SPY_WINS to "Victoires Espions",
        StringKey.HOST_CLOUD_SYNC to "Sauvegarde Cloud (Optionnel)",
        StringKey.HOST_CLOUD_SYNC_DESC to "Connectez-vous avec Google pour sauvegarder vos stats sur Firestore.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Connexion avec Google",
        StringKey.SIGNED_IN_AS to "Connecté en tant que :",
        StringKey.SIGN_OUT to "Déconnexion",
        StringKey.SYNC_NOW to "Synchroniser",
        StringKey.SYNC_SUCCESS to "Sauvegarde cloud réussie !",
        StringKey.ADD_NEW_WORD to "Ajouter un Mot",
        StringKey.WORD_INPUT_HINT to "Mot secret...",
        StringKey.CATEGORY_INPUT_HINT to "Catégorie...",
        StringKey.SAVE_WORD to "Enregistrer",
        StringKey.DELETE_WORD to "Supprimer",
        StringKey.NO_CUSTOM_WORDS to "Aucun mot personnalisé.",
        StringKey.BACK to "Retour",
        StringKey.CLOSE to "Fermer",
        StringKey.SAVE to "Enregistrer",
        StringKey.CANCEL to "Annuler",
        StringKey.RESET to "Réinitialiser",
        StringKey.CONFIRM to "Confirmer",
        StringKey.ERROR_MIN_PLAYERS to "Au moins 3 joueurs sont requis !",
        StringKey.ERROR_TOO_MANY_SPIES to "Trop d'espions pour ce nombre de joueurs !",
        StringKey.ERROR_SELECT_CATEGORY to "Veuillez sélectionner au moins une catégorie !",
        StringKey.CAT_ANIMALS to "Animaux",
        StringKey.CAT_FOOD to "Nourriture",
        StringKey.CAT_COUNTRIES to "Pays",
        StringKey.CAT_CITIES to "Villes",
        StringKey.CAT_OBJECTS to "Objets",
        StringKey.CAT_TECHNOLOGY to "Technologie",
        StringKey.CAT_VIDEOGAMES to "Jeux Vidéo",
        StringKey.CAT_MOVIES to "Cinéma",
        StringKey.CAT_SPORTS to "Sports",
        StringKey.CAT_CELEBRITIES to "Célébrités",
        StringKey.CAT_VEHICLES to "Véhicules",
        StringKey.CAT_NATURE to "Nature",
        StringKey.CAT_JOBS to "Métiers",
        StringKey.CAT_SCHOOL to "École",
        StringKey.CAT_RANDOM to "Aléatoire"
    )

    private val germanMap = mapOf(
        StringKey.APP_NAME to "SPION",
        StringKey.TAGLINE to "Findest du den Spion?",
        StringKey.PLAY to "SPIELEN",
        StringKey.CUSTOM_GAME to "BENUTZERDEFINIERT",
        StringKey.HOW_TO_PLAY to "SPIELREGELN",
        StringKey.SETTINGS to "EINSTELLUNGEN",
        StringKey.HISTORY to "SPIELVERLAUF",
        StringKey.CUSTOM_WORDS to "EIGENE WÖRTER",
        StringKey.START_GAME to "RUNDE STARTEN",
        StringKey.PLAYERS_COUNT to "Spieler",
        StringKey.SPIES_COUNT to "Spione",
        StringKey.PLAYER_NAMES to "Spielernamen",
        StringKey.ADD_PLAYER to "Spieler hinzufügen",
        StringKey.REMOVE_PLAYER to "Entfernen",
        StringKey.SPY_CLUES_TITLE to "Spion-Hinweise",
        StringKey.CLUE_NONE to "Kein Hinweis",
        StringKey.CLUE_NONE_DESC to "Der Spion erhält keinerlei Infos",
        StringKey.CLUE_CATEGORY to "Kategorie-Hinweis",
        StringKey.CLUE_CATEGORY_DESC to "Der Spion kennt die Kategorie",
        StringKey.CLUE_FIRST_LETTER to "Anfangsbuchstabe",
        StringKey.CLUE_FIRST_LETTER_DESC to "Der Spion kennt den 1. Buchstaben",
        StringKey.CLUE_WORD_CATEGORY to "Kategorie & Wortlänge",
        StringKey.CLUE_WORD_CATEGORY_DESC to "Der Spion kennt Kategorie und Länge",
        StringKey.ROUND_SETTINGS to "Rundeneinstellungen",
        StringKey.DISCUSSION_TIMER to "Diskussionstimer",
        StringKey.TIMER_OFF to "Aus",
        StringKey.TIMER_30S to "30s",
        StringKey.TIMER_60S to "60s",
        StringKey.TIMER_90S to "90s",
        StringKey.TIMER_2M to "2 Min",
        StringKey.TIMER_CUSTOM to "Benutzerdefiniert",
        StringKey.SOUND_EFFECTS to "Soundeffekte",
        StringKey.VIBRATION to "Vibration",
        StringKey.PREVENT_REPEATED_WORDS to "Wortwiederholung vermeiden",
        StringKey.CATEGORIES_TITLE to "Wortkategorien",
        StringKey.SELECT_ALL to "Alle auswählen",
        StringKey.DESELECT_ALL to "Alle abwählen",
        StringKey.DIFFICULTY_TITLE to "Schwierigkeit",
        StringKey.DIFF_EASY to "Einfach",
        StringKey.DIFF_MEDIUM to "Mittel",
        StringKey.DIFF_HARD to "Schwer",
        StringKey.DIFF_EXTREME to "Extrem",
        StringKey.WORD_LENGTH_TITLE to "Wortlänge",
        StringKey.LENGTH_ANY to "Beliebig",
        StringKey.LENGTH_SHORT to "Kurz (3-5 Buchstaben)",
        StringKey.LENGTH_MEDIUM to "Mittel (6-8 Buchstaben)",
        StringKey.LENGTH_LONG to "Lang (9+ Buchstaben)",
        StringKey.PASS_PHONE_TO to "GIB DAS SMARTPHONE AN %s",
        StringKey.GET_READY_PROMPT to "Achte darauf, dass niemand auf den Bildschirm schaut!",
        StringKey.REVEAL_MY_ROLE to "MEINE ROLLE ZEIGEN",
        StringKey.YOU_ARE_INNOCENT to "🟢 DU BIST UNSCHULDIG",
        StringKey.YOU_ARE_SPY to "🔴 DU BIST DER SPION",
        StringKey.SECRET_WORD_IS to "GEHEIMWORT",
        StringKey.CATEGORY_LABEL to "KATEGORIE",
        StringKey.SPY_CLUE_LABEL to "SPION-HINWEIS",
        StringKey.INNOCENT_HINT to "Du kennst das Geheimwort. Gib schlaue Hinweise, ohne dass der Spion es errät!",
        StringKey.SPY_HINT to "Du kennst das Wort nicht! Hör gut zu, pass dich an und versuche es zu erraten!",
        StringKey.HIDE_AND_PASS to "VERBERGEN & WEITERGEBEN",
        StringKey.ALL_ROLES_REVEALED_TITLE to "ALLE SIND BEREIT!",
        StringKey.ALL_ROLES_REVEALED_DESC to "Legt das Smartphone auf den Tisch. Diskutiert jetzt im echten Leben!",
        StringKey.START_DISCUSSION to "DISKUSSION STARTEN",
        StringKey.DISCUSSION_TITLE to "DISKUSSION LÄUFT",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s gibt den ersten Hinweis!",
        StringKey.TIME_REMAINING to "Verbleibende Zeit",
        StringKey.PAUSE to "Pause",
        StringKey.RESUME to "Weiter",
        StringKey.ADD_30S to "+30s",
        StringKey.TIME_TO_VOTE to "ZEIT ZUR ABSTIMMUNG",
        StringKey.TIME_TO_VOTE_TITLE to "Jetzt abstimmen!",
        StringKey.TIME_TO_VOTE_DESC to "Zeigt alle auf die Person, die ihr für den Spion haltet.",
        StringKey.WHO_WAS_THE_SPY to "WER WURDE ALS SPION BESCHULDIGT?",
        StringKey.CONFIRM_ACCUSATION to "VOTUM BESTÄTIGEN",
        StringKey.SPY_WAS_CAUGHT to "🔴 DER SPION WURDE ENTDECKT!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 EIN UNSCHULDIGER WURDE VERDÄCHTIGT!",
        StringKey.SPY_LAST_CHANCE_TITLE to "LETZTE CHANCE DES SPIONS!",
        StringKey.SPY_LAST_CHANCE_DESC to "Konnte der Spion das Geheimwort erraten?",
        StringKey.SPY_GUESSED_CORRECT to "SPION HAT ES ERRATEN",
        StringKey.SPY_GUESSED_WRONG to "SPION LAG FALSCH",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ DER SPION SCHNAPPTE SICH DEN SIEG!",
        StringKey.PLAYERS_WIN to "🎉 DIE UNSCHULDIGEN GEWINNEN!",
        StringKey.SPIES_WIN to "🕵️ DIE SPIONE GEWINNEN!",
        StringKey.REVEALED_WORD_WAS to "Das Geheimwort war:",
        StringKey.THE_REAL_SPIES_WERE to "Der echte Spion war:",
        StringKey.PLAY_NEXT_ROUND to "NÄCHSTE RUNDE",
        StringKey.CHANGE_SETTINGS to "EINSTELLUNGEN ÄNDERN",
        StringKey.RETURN_HOME to "HAUPTMENÜ",
        StringKey.RULE_1_TITLE to "1. Smartphone weitergeben",
        StringKey.RULE_1_DESC to "Jeder Spieler tippt geheim auf seine Rolle. Unschuldige sehen das Wort, der Spion nicht!",
        StringKey.RULE_2_TITLE to "2. Hinweise geben",
        StringKey.RULE_2_DESC to "Legt das Telefon weg. Jeder gibt nacheinander einen dezenten Hinweis.",
        StringKey.RULE_3_TITLE to "3. Abstimmung",
        StringKey.RULE_3_DESC to "Stimmt ab, wer der Spion ist, und wählt die Person in der App aus.",
        StringKey.RULE_4_TITLE to "4. Letzte Chance",
        StringKey.RULE_4_DESC to "Wird der Spion enttarnt, darf er einmal versuchen, das Wort zu erraten.",
        StringKey.SELECT_LANGUAGE to "Sprache wählen",
        StringKey.LANGUAGE to "Sprache",
        StringKey.TOTAL_GAMES_PLAYED to "Gespielte Runden",
        StringKey.INNOCENT_WINS to "Siege Unschuldige",
        StringKey.SPY_WINS to "Siege Spione",
        StringKey.HOST_CLOUD_SYNC to "Cloud-Backup (Optional)",
        StringKey.HOST_CLOUD_SYNC_DESC to "Mit Google anmelden, um Spielstatistiken in Firebase zu sichern.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Mit Google anmelden",
        StringKey.SIGNED_IN_AS to "Angemeldet als:",
        StringKey.SIGN_OUT to "Abmelden",
        StringKey.SYNC_NOW to "Synchronisieren",
        StringKey.SYNC_SUCCESS to "Erfolgreich in Cloud gesichert!",
        StringKey.ADD_NEW_WORD to "Neues Wort hinzufügen",
        StringKey.WORD_INPUT_HINT to "Geheimwort...",
        StringKey.CATEGORY_INPUT_HINT to "Kategorie...",
        StringKey.SAVE_WORD to "Speichern",
        StringKey.DELETE_WORD to "Löschen",
        StringKey.NO_CUSTOM_WORDS to "Keine eigenen Wörter vorhanden.",
        StringKey.BACK to "Zurück",
        StringKey.CLOSE to "Schließen",
        StringKey.SAVE to "Speichern",
        StringKey.CANCEL to "Abbrechen",
        StringKey.RESET to "Zurücksetzen",
        StringKey.CONFIRM to "Bestätigen",
        StringKey.ERROR_MIN_PLAYERS to "Mindestens 3 Spieler erforderlich!",
        StringKey.ERROR_TOO_MANY_SPIES to "Zu viele Spione für diese Spieleranzahl!",
        StringKey.ERROR_SELECT_CATEGORY to "Wähle mindestens eine Kategorie aus!",
        StringKey.CAT_ANIMALS to "Tiere",
        StringKey.CAT_FOOD to "Essen",
        StringKey.CAT_COUNTRIES to "Länder",
        StringKey.CAT_CITIES to "Städte",
        StringKey.CAT_OBJECTS to "Gegenstände",
        StringKey.CAT_TECHNOLOGY to "Technologie",
        StringKey.CAT_VIDEOGAMES to "Videospiele",
        StringKey.CAT_MOVIES to "Filme",
        StringKey.CAT_SPORTS to "Sport",
        StringKey.CAT_CELEBRITIES to "Prominente",
        StringKey.CAT_VEHICLES to "Fahrzeuge",
        StringKey.CAT_NATURE to "Natur",
        StringKey.CAT_JOBS to "Berufe",
        StringKey.CAT_SCHOOL to "Schule",
        StringKey.CAT_RANDOM to "Zufall"
    )

    private val russianMap = mapOf(
        StringKey.APP_NAME to "ШПИОН",
        StringKey.TAGLINE to "Сможете ли вы найти Шпиона?",
        StringKey.PLAY to "ИГРАТЬ",
        StringKey.CUSTOM_GAME to "СВОЯ ИГРА",
        StringKey.HOW_TO_PLAY to "КАК ИГРАТЬ",
        StringKey.SETTINGS to "НАСТРОЙКИ",
        StringKey.HISTORY to "ИСТОРИЯ ИГР",
        StringKey.CUSTOM_WORDS to "СВОИ СЛОВА",
        StringKey.START_GAME to "НАЧАТЬ РАУНД",
        StringKey.PLAYERS_COUNT to "Игроки",
        StringKey.SPIES_COUNT to "Шпионы",
        StringKey.PLAYER_NAMES to "Имена игроков",
        StringKey.ADD_PLAYER to "Добавить игрока",
        StringKey.REMOVE_PLAYER to "Удалить",
        StringKey.SPY_CLUES_TITLE to "Подсказки шпиону",
        StringKey.CLUE_NONE to "Без подсказок",
        StringKey.CLUE_NONE_DESC to "Шпион не знает ничего о слове",
        StringKey.CLUE_CATEGORY to "Подсказка категории",
        StringKey.CLUE_CATEGORY_DESC to "Шпион знает категорию слова",
        StringKey.CLUE_FIRST_LETTER to "Первая буква",
        StringKey.CLUE_FIRST_LETTER_DESC to "Шпион знает первую букву слова",
        StringKey.CLUE_WORD_CATEGORY to "Категория и длина",
        StringKey.CLUE_WORD_CATEGORY_DESC to "Шпион знает категорию и длину",
        StringKey.ROUND_SETTINGS to "Настройки раунда",
        StringKey.DISCUSSION_TIMER to "Таймер обсуждения",
        StringKey.TIMER_OFF to "Выкл",
        StringKey.TIMER_30S to "30 сек",
        StringKey.TIMER_60S to "1 мин",
        StringKey.TIMER_90S to "90 сек",
        StringKey.TIMER_2M to "2 мин",
        StringKey.TIMER_CUSTOM to "Свой",
        StringKey.SOUND_EFFECTS to "Звуковые эффекты",
        StringKey.VIBRATION to "Вибрация",
        StringKey.PREVENT_REPEATED_WORDS to "Без повторов слов",
        StringKey.CATEGORIES_TITLE to "Категории слов",
        StringKey.SELECT_ALL to "Выбрать все",
        StringKey.DESELECT_ALL to "Снять все",
        StringKey.DIFFICULTY_TITLE to "Сложность",
        StringKey.DIFF_EASY to "Легко",
        StringKey.DIFF_MEDIUM to "Средне",
        StringKey.DIFF_HARD to "Сложно",
        StringKey.DIFF_EXTREME to "Экстрим",
        StringKey.WORD_LENGTH_TITLE to "Длина слова",
        StringKey.LENGTH_ANY to "Любая",
        StringKey.LENGTH_SHORT to "Короткие (3-5 букв)",
        StringKey.LENGTH_MEDIUM to "Средние (6-8 букв)",
        StringKey.LENGTH_LONG to "Длинные (9+ букв)",
        StringKey.PASS_PHONE_TO to "ПЕРЕДАЙТЕ ТЕЛЕФОН %s",
        StringKey.GET_READY_PROMPT to "Убедитесь, что никто не подглядывает в экран!",
        StringKey.REVEAL_MY_ROLE to "ПОСМОТРЕТЬ РОЛЬ",
        StringKey.YOU_ARE_INNOCENT to "🟢 ВЫ МЕСТНЫЙ ЖИТЕЛЬ",
        StringKey.YOU_ARE_SPY to "🔴 ВЫ ШПИОН",
        StringKey.SECRET_WORD_IS to "СЕКРЕТНОЕ СЛОВО",
        StringKey.CATEGORY_LABEL to "КАТЕГОРИЯ",
        StringKey.SPY_CLUE_LABEL to "ПОДСКАЗКА ШПИОНУ",
        StringKey.INNOCENT_HINT to "Вы знаете секретное слово. Давайте осторожные подсказки, чтобы не выдать его шпиону!",
        StringKey.SPY_HINT to "Вы не знаете слово! Внимательно слушайте других и попробуйте догадаться!",
        StringKey.HIDE_AND_PASS to "СКРЫТЬ И ПЕРЕДАТЬ ТЕЛЕФОН",
        StringKey.ALL_ROLES_REVEALED_TITLE to "ВСЕ ГОТОВЫ!",
        StringKey.ALL_ROLES_REVEALED_DESC to "Положите телефон на стол. Начинайте обсуждение вслух.",
        StringKey.START_DISCUSSION to "НАЧАТЬ ОБСУЖДЕНИЕ",
        StringKey.DISCUSSION_TITLE to "ИДЕТ ОБСУЖДЕНИЕ",
        StringKey.FIRST_CLUE_PROMPT to "🎲 %s дает первую подсказку!",
        StringKey.TIME_REMAINING to "Осталось времени",
        StringKey.PAUSE to "Пауза",
        StringKey.RESUME to "Продолжить",
        StringKey.ADD_30S to "+30 сек",
        StringKey.TIME_TO_VOTE to "ВРЕМЯ ГОЛОСОВАТЬ",
        StringKey.TIME_TO_VOTE_TITLE to "Голосуйте прямо сейчас!",
        StringKey.TIME_TO_VOTE_DESC to "Обсудите и укажите на того, кого считаете шпионом.",
        StringKey.WHO_WAS_THE_SPY to "КОГО ОБВИНИЛИ В ШПИОНАЖЕ?",
        StringKey.CONFIRM_ACCUSATION to "ПОДТВЕРДИТЬ ВЫБОР",
        StringKey.SPY_WAS_CAUGHT to "🔴 ШПИОН БЫЛ РАСКРЫТ!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 ОБВИНИЛИ НЕВИНОВНОГО!",
        StringKey.SPY_LAST_CHANCE_TITLE to "ПОСЛЕДНИЙ ШАНС ШПИОНА!",
        StringKey.SPY_LAST_CHANCE_DESC to "Смог ли шпион угадать секретное слово прямо сейчас?",
        StringKey.SPY_GUESSED_CORRECT to "ШПИОН УГАДАЛ СЛОВО",
        StringKey.SPY_GUESSED_WRONG to "ШПИОН ОШИБСЯ",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ ШПИОН УКРАЛ ПОБЕДУ!",
        StringKey.PLAYERS_WIN to "🎉 МЕСТНЫЕ ЖИТЕЛИ ПОБЕДИЛИ!",
        StringKey.SPIES_WIN to "🕵️ ШПИОНЫ ПОБЕДИЛИ!",
        StringKey.REVEALED_WORD_WAS to "Секретным словом было:",
        StringKey.THE_REAL_SPIES_WERE to "Настоящий шпион:",
        StringKey.PLAY_NEXT_ROUND to "СЛЕДУЮЩИЙ РАУНД",
        StringKey.CHANGE_SETTINGS to "ИЗМЕНИТЬ НАСТРОЙКИ",
        StringKey.RETURN_HOME to "В ГЛАВНОЕ МЕНЮ",
        StringKey.RULE_1_TITLE to "1. Передача телефона",
        StringKey.RULE_1_DESC to "Каждый игрок тайно смотрит свою роль. Местные видят слово, шпион не видит!",
        StringKey.RULE_2_TITLE to "2. Подсказки и беседы",
        StringKey.RULE_2_DESC to "Положите телефон. По очереди давайте тонкие ассоциации.",
        StringKey.RULE_3_TITLE to "3. Голосование",
        StringKey.RULE_3_DESC to "Проголосуйте за шпиона, и ведущий отметит выбор в приложении.",
        StringKey.RULE_4_TITLE to "4. Шанс шпиона",
        StringKey.RULE_4_DESC to "Если шпиона поймали, он может назвать слово и вырвать победу!",
        StringKey.SELECT_LANGUAGE to "Выбрать язык",
        StringKey.LANGUAGE to "Язык",
        StringKey.TOTAL_GAMES_PLAYED to "Всего сыграно",
        StringKey.INNOCENT_WINS to "Побед мирных",
        StringKey.SPY_WINS to "Побед шпиона",
        StringKey.HOST_CLOUD_SYNC to "Облачный бэкап (Опционально)",
        StringKey.HOST_CLOUD_SYNC_DESC to "Войдите с Google для синхронизации в Firebase.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Войти через Google",
        StringKey.SIGNED_IN_AS to "Вы вошли как:",
        StringKey.SIGN_OUT to "Выйти",
        StringKey.SYNC_NOW to "Синхронизировать",
        StringKey.SYNC_SUCCESS to "Данные сохранены в облаке!",
        StringKey.ADD_NEW_WORD to "Добавить слово",
        StringKey.WORD_INPUT_HINT to "Секретное слово...",
        StringKey.CATEGORY_INPUT_HINT to "Категория...",
        StringKey.SAVE_WORD to "Сохранить",
        StringKey.DELETE_WORD to "Удалить",
        StringKey.NO_CUSTOM_WORDS to "Своих слов пока нет.",
        StringKey.BACK to "Назад",
        StringKey.CLOSE to "Закрыть",
        StringKey.SAVE to "Сохранить",
        StringKey.CANCEL to "Отмена",
        StringKey.RESET to "Сброс",
        StringKey.CONFIRM to "Подтвердить",
        StringKey.ERROR_MIN_PLAYERS to "Минимум 3 игрока!",
        StringKey.ERROR_TOO_MANY_SPIES to "Слишком много шпионов для такого числа игроков!",
        StringKey.ERROR_SELECT_CATEGORY to "Выберите хотя бы одну категорию!",
        StringKey.CAT_ANIMALS to "Животные",
        StringKey.CAT_FOOD to "Еда",
        StringKey.CAT_COUNTRIES to "Страны",
        StringKey.CAT_CITIES to "Города",
        StringKey.CAT_OBJECTS to "Предметы",
        StringKey.CAT_TECHNOLOGY to "Технологии",
        StringKey.CAT_VIDEOGAMES to "Видеоигры",
        StringKey.CAT_MOVIES to "Фильмы",
        StringKey.CAT_SPORTS to "Спорт",
        StringKey.CAT_CELEBRITIES to "Знаменитости",
        StringKey.CAT_VEHICLES to "Транспорт",
        StringKey.CAT_NATURE to "Природа",
        StringKey.CAT_JOBS to "Профессии",
        StringKey.CAT_SCHOOL to "Школа",
        StringKey.CAT_RANDOM to "Случайные"
    )

    private val turkishMap = mapOf(
        StringKey.APP_NAME to "CASUS",
        StringKey.TAGLINE to "Casusu bulabilir misin?",
        StringKey.PLAY to "OYNA",
        StringKey.CUSTOM_GAME to "ÖZEL OYUN",
        StringKey.HOW_TO_PLAY to "NASIL OYNANIR",
        StringKey.SETTINGS to "AYARLAR",
        StringKey.HISTORY to "GEÇMİŞ",
        StringKey.CUSTOM_WORDS to "ÖZEL KELİMELER",
        StringKey.START_GAME to "TURU BAŞLAT",
        StringKey.PLAYERS_COUNT to "Oyuncular",
        StringKey.SPIES_COUNT to "Casuslar",
        StringKey.PLAYER_NAMES to "Oyuncu İsimleri",
        StringKey.ADD_PLAYER to "Oyuncu Ekle",
        StringKey.REMOVE_PLAYER to "Kaldır",
        StringKey.SPY_CLUES_TITLE to "Casus İpuçları",
        StringKey.CLUE_NONE to "İpucu Yok",
        StringKey.CLUE_NONE_DESC to "Casus hiçbir şey bilmez",
        StringKey.CLUE_CATEGORY to "Kategori İpucu",
        StringKey.CLUE_CATEGORY_DESC to "Casus kelimenin kategorisini bilir",
        StringKey.CLUE_FIRST_LETTER to "İlk Harf İpucu",
        StringKey.CLUE_FIRST_LETTER_DESC to "Casus ilk harfi bilir",
        StringKey.CLUE_WORD_CATEGORY to "Kategori ve Uzunluk",
        StringKey.CLUE_WORD_CATEGORY_DESC to "Casus kategori ve harf sayısını bilir",
        StringKey.ROUND_SETTINGS to "Tur Ayarları",
        StringKey.DISCUSSION_TIMER to "Tartışma Sayacı",
        StringKey.TIMER_OFF to "Kapalı",
        StringKey.TIMER_30S to "30 sn",
        StringKey.TIMER_60S to "60 sn",
        StringKey.TIMER_90S to "90 sn",
        StringKey.TIMER_2M to "2 dk",
        StringKey.TIMER_CUSTOM to "Özel",
        StringKey.SOUND_EFFECTS to "Ses Efektleri",
        StringKey.VIBRATION to "Titreşim",
        StringKey.PREVENT_REPEATED_WORDS to "Kelime Tekrarını Önle",
        StringKey.CATEGORIES_TITLE to "Kategoriler",
        StringKey.SELECT_ALL to "Tümünü Seç",
        StringKey.DESELECT_ALL to "Tümünü Kaldır",
        StringKey.DIFFICULTY_TITLE to "Zorluk",
        StringKey.DIFF_EASY to "Kolay",
        StringKey.DIFF_MEDIUM to "Orta",
        StringKey.DIFF_HARD to "Zor",
        StringKey.DIFF_EXTREME to "Çok Zor",
        StringKey.WORD_LENGTH_TITLE to "Kelime Uzunluğu",
        StringKey.LENGTH_ANY to "Farketmez",
        StringKey.LENGTH_SHORT to "Kısa (3-5 harf)",
        StringKey.LENGTH_MEDIUM to "Orta (6-8 harf)",
        StringKey.LENGTH_LONG to "Uzun (+9 harf)",
        StringKey.PASS_PHONE_TO to "TELEFONU %s ADLI OYUNCUYA VERİN",
        StringKey.GET_READY_PROMPT to "Ekrana başka kimsenin bakmadığından emin olun!",
        StringKey.REVEAL_MY_ROLE to "ROLÜMÜ GÖSTER",
        StringKey.YOU_ARE_INNOCENT to "🟢 MASUMSUNUZ",
        StringKey.YOU_ARE_SPY to "🔴 SİZ CASUSSUNUZ",
        StringKey.SECRET_WORD_IS to "GİZLİ KELİME",
        StringKey.CATEGORY_LABEL to "KATEGORİ",
        StringKey.SPY_CLUE_LABEL to "CASUS İPUCU",
        StringKey.INNOCENT_HINT to "Gizli kelimeyi biliyorsunuz. Casusa belli etmeden akıllıca ipuçları verin!",
        StringKey.SPY_HINT to "Kelimeyi bilmiyorsunuz! Herkesi dikkatle dinleyin ve gizli kelimeyi tahmin edin!",
        StringKey.HIDE_AND_PASS to "GİZLE VE DEVRET",
        StringKey.ALL_ROLES_REVEALED_TITLE to "HERKES HAZIR!",
        StringKey.ALL_ROLES_REVEALED_DESC to "Telefonu masaya koyun. Gerçek hayatta tartışma başlasın!",
        StringKey.START_DISCUSSION to "TARTIŞMAYI BAŞLAT",
        StringKey.DISCUSSION_TITLE to "TARTIŞMA SÜRÜYOR",
        StringKey.FIRST_CLUE_PROMPT to "🎲 İlk ipucunu %s veriyor!",
        StringKey.TIME_REMAINING to "Kalan Süre",
        StringKey.PAUSE to "Duraklat",
        StringKey.RESUME to "Devam Et",
        StringKey.ADD_30S to "+30 sn",
        StringKey.TIME_TO_VOTE to "OYLAMA VAKTİ",
        StringKey.TIME_TO_VOTE_TITLE to "Şimdi oy verin!",
        StringKey.TIME_TO_VOTE_DESC to "Casus olduğunu düşündüğünüz kişiyi işaret edin.",
        StringKey.WHO_WAS_THE_SPY to "KİM CASUS OLARAK SEÇİLDİ?",
        StringKey.CONFIRM_ACCUSATION to "OYU ONAYLA",
        StringKey.SPY_WAS_CAUGHT to "🔴 CASUS YAKALANDI!",
        StringKey.INNOCENT_WAS_ACCUSED to "🟢 MASUM BİRİ SUÇLANDI!",
        StringKey.SPY_LAST_CHANCE_TITLE to "CASUSUN SON ŞANSI!",
        StringKey.SPY_LAST_CHANCE_DESC to "Casus gizli kelimeyi bildi mi?",
        StringKey.SPY_GUESSED_CORRECT to "CASUS KELİMEYİ BİLDİ",
        StringKey.SPY_GUESSED_WRONG to "CASUS BİLEMEDİ",
        StringKey.SPY_STOLE_THE_WIN to "🕵️ CASUS ZAFERİ ÇALDI!",
        StringKey.PLAYERS_WIN to "🎉 MASUMLAR KAZANDI!",
        StringKey.SPIES_WIN to "🕵️ CASUSLAR KAZANDI!",
        StringKey.REVEALED_WORD_WAS to "Gizli kelime şuydu:",
        StringKey.THE_REAL_SPIES_WERE to "Gerçek casus:",
        StringKey.PLAY_NEXT_ROUND to "SONRAKİ TUR",
        StringKey.CHANGE_SETTINGS to "AYARLARI DEĞİŞTİR",
        StringKey.RETURN_HOME to "ANA MENÜ",
        StringKey.RULE_1_TITLE to "1. Telefonu Devret",
        StringKey.RULE_1_DESC to "Her oyuncu gizlice rolüne bakar. Masumlar kelimeyi görür, casus göremez!",
        StringKey.RULE_2_TITLE to "2. İpuçları ve Sohbet",
        StringKey.RULE_2_DESC to "Telefonu bırakın. Sırayla kelimeyle ilgili ince ipuçları verin.",
        StringKey.RULE_3_TITLE to "3. Oylama",
        StringKey.RULE_3_DESC to "Casusun kim olduğunu oylayın ve ekranda işaretleyin.",
        StringKey.RULE_4_TITLE to "4. Casusun Son Şansı",
        StringKey.RULE_4_DESC to "Casus yakalansa bile kelimeyi tahmin ederek kazanabilir!",
        StringKey.SELECT_LANGUAGE to "Dil Seç",
        StringKey.LANGUAGE to "Dil",
        StringKey.TOTAL_GAMES_PLAYED to "Toplam Oyun",
        StringKey.INNOCENT_WINS to "Masum Galibiyeti",
        StringKey.SPY_WINS to "Casus Galibiyeti",
        StringKey.HOST_CLOUD_SYNC to "Bulut Yedekleme (İsteğe Bağlı)",
        StringKey.HOST_CLOUD_SYNC_DESC to "İstatistikleri Firebase Firestore'da saklamak için Google ile giriş yapın.",
        StringKey.SIGN_IN_WITH_GOOGLE to "Google ile Giriş Yap",
        StringKey.SIGNED_IN_AS to "Giriş yapıldı:",
        StringKey.SIGN_OUT to "Çıkış Yap",
        StringKey.SYNC_NOW to "Eşitle",
        StringKey.SYNC_SUCCESS to "Buluta başarıyla yedeklendi!",
        StringKey.ADD_NEW_WORD to "Özel Kelime Ekle",
        StringKey.WORD_INPUT_HINT to "Gizli kelime...",
        StringKey.CATEGORY_INPUT_HINT to "Kategori...",
        StringKey.SAVE_WORD to "Kaydet",
        StringKey.DELETE_WORD to "Sil",
        StringKey.NO_CUSTOM_WORDS to "Henüz özel kelime yok.",
        StringKey.BACK to "Geri",
        StringKey.CLOSE to "Kapat",
        StringKey.SAVE to "Kaydet",
        StringKey.CANCEL to "İptal",
        StringKey.RESET to "Sıfırla",
        StringKey.CONFIRM to "Onayla",
        StringKey.ERROR_MIN_PLAYERS to "En az 3 oyuncu gereklidir!",
        StringKey.ERROR_TOO_MANY_SPIES to "Bu oyuncu sayısı için çok fazla casus!",
        StringKey.ERROR_SELECT_CATEGORY to "Lütfen en az bir kategori seçin!",
        StringKey.CAT_ANIMALS to "Hayvanlar",
        StringKey.CAT_FOOD to "Yiyecekler",
        StringKey.CAT_COUNTRIES to "Ülkeler",
        StringKey.CAT_CITIES to "Şehirler",
        StringKey.CAT_OBJECTS to "Eşyalar",
        StringKey.CAT_TECHNOLOGY to "Teknoloji",
        StringKey.CAT_VIDEOGAMES to "Video Oyunları",
        StringKey.CAT_MOVIES to "Filmler",
        StringKey.CAT_SPORTS to "Spor",
        StringKey.CAT_CELEBRITIES to "Ünlüler",
        StringKey.CAT_VEHICLES to "Araçlar",
        StringKey.CAT_NATURE to "Doğa",
        StringKey.CAT_JOBS to "Meslekler",
        StringKey.CAT_SCHOOL to "Okul",
        StringKey.CAT_RANDOM to "Rastgele"
    )

    private val translations: Map<Language, Map<StringKey, String>> = mapOf(
        Language.ENGLISH to englishMap,
        Language.PERSIAN to persianMap,
        Language.ARABIC to arabicMap,
        Language.SPANISH to spanishMap,
        Language.FRENCH to frenchMap,
        Language.GERMAN to germanMap,
        Language.RUSSIAN to russianMap,
        Language.TURKISH to turkishMap,
        // For remaining languages, fallback seamlessly to curated multilingual maps or English
        Language.ITALIAN to englishMap.mapValues { (k, v) ->
            when (k) {
                StringKey.APP_NAME -> "SPIA"
                StringKey.TAGLINE -> "Riuscirai a trovare la Spia?"
                StringKey.PLAY -> "GIOCA"
                StringKey.YOU_ARE_INNOCENT -> "🟢 SEI INNOCENTE"
                StringKey.YOU_ARE_SPY -> "🔴 SEI LA SPIA"
                StringKey.SECRET_WORD_IS -> "PAROLA SEGRETA"
                StringKey.HIDE_AND_PASS -> "NASCONDI E PASSA"
                StringKey.TIME_TO_VOTE -> "ORA DI VOTARE"
                StringKey.PLAY_NEXT_ROUND -> "PROSSIMO TURNO"
                else -> v
            }
        },
        Language.PORTUGUESE to englishMap.mapValues { (k, v) ->
            when (k) {
                StringKey.APP_NAME -> "ESPIÃO"
                StringKey.TAGLINE -> "Você consegue achar o Espião?"
                StringKey.PLAY -> "JOGAR"
                StringKey.YOU_ARE_INNOCENT -> "🟢 VOCÊ É INOCENTE"
                StringKey.YOU_ARE_SPY -> "🔴 VOCÊ É O ESPIÃO"
                StringKey.SECRET_WORD_IS -> "PALAVRA SECRETA"
                StringKey.HIDE_AND_PASS -> "OCULTAR E PASSAR"
                StringKey.TIME_TO_VOTE -> "HORA DE VOTAR"
                StringKey.PLAY_NEXT_ROUND -> "PRÓXIMA RODADA"
                else -> v
            }
        },
        Language.JAPANESE to englishMap.mapValues { (k, v) ->
            when (k) {
                StringKey.APP_NAME -> "スパイ"
                StringKey.TAGLINE -> "スパイを見つけられるか？"
                StringKey.PLAY -> "プレイ"
                StringKey.YOU_ARE_INNOCENT -> "🟢 あなたは一般人です"
                StringKey.YOU_ARE_SPY -> "🔴 あなたはスパイです"
                StringKey.SECRET_WORD_IS -> "秘密の言葉"
                StringKey.HIDE_AND_PASS -> "隠してスマホを渡す"
                StringKey.TIME_TO_VOTE -> "投票タイム"
                StringKey.PLAY_NEXT_ROUND -> "次のラウンド"
                else -> v
            }
        },
        Language.KOREAN to englishMap.mapValues { (k, v) ->
            when (k) {
                StringKey.APP_NAME -> "스파이"
                StringKey.TAGLINE -> "스파이를 찾아낼 수 있나요?"
                StringKey.PLAY -> "게임 시작"
                StringKey.YOU_ARE_INNOCENT -> "🟢 당신은 시민입니다"
                StringKey.YOU_ARE_SPY -> "🔴 당신은 스파이입니다"
                StringKey.SECRET_WORD_IS -> "비밀 단어"
                StringKey.HIDE_AND_PASS -> "숨기고 폰 넘기기"
                StringKey.TIME_TO_VOTE -> "투표 시간"
                StringKey.PLAY_NEXT_ROUND -> "다음 라운드"
                else -> v
            }
        },
        Language.CHINESE to englishMap.mapValues { (k, v) ->
            when (k) {
                StringKey.APP_NAME -> "间谍"
                StringKey.TAGLINE -> "你能找出卧底间谍吗？"
                StringKey.PLAY -> "开始游戏"
                StringKey.YOU_ARE_INNOCENT -> "🟢 你是平民"
                StringKey.YOU_ARE_SPY -> "🔴 你是间谍"
                StringKey.SECRET_WORD_IS -> "秘密词语"
                StringKey.HIDE_AND_PASS -> "隐藏并传递手机"
                StringKey.TIME_TO_VOTE -> "投票时间"
                StringKey.PLAY_NEXT_ROUND -> "下一轮"
                else -> v
            }
        }
    )
}
